name: Auto Test

on:
  schedule:
    - cron: '0 6,18 * * *'
  push:
  pull_request:
  workflow_dispatch:

jobs:
  autotest:
    if: ${{ github.repository_owner == 'Chewawu' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      
      - name: Cache node modules
        id: cache
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: bun test
